add username to debug
astrolabsoftware/fink-filters pull request #214
Opened 2024-12-25 07:44 UTC by Knispel2

We have a little problem: for some reason, it is not possible to login to all accounts except `beta` in [this line](https://github.com/astrolabsoftware/fink-filters/blob/master/fink_filters/filter_anomaly_notification/filter_utils.py#L295). I suspect that for some reason the wrong usernames are being passed to `username`, but I can't figure out the reason yet. I want to add the contents of `username` to the error messages

2025-01-06 06:52 UTC, JulienPeloton requested changes

2025-01-06 06:52 UTC, JulienPeloton commented on fink_filters/filter_anomaly_notification/filter.py
> +    >>> from fink_science.anomaly_detection.processor import ANOMALY_MODELS
This is not required?

2025-01-09 13:41 UTC, Knispel2 commented on fink_filters/filter_anomaly_notification/filter.py
> +    >>> from fink_science.anomaly_detection.processor import ANOMALY_MODELS
Yes, I just forgot to delete it after my experiments

2025-01-09 14:07 UTC, JulienPeloton approved these changes

2025-01-09 14:09 UTC, JulienPeloton commented
Thanks @Knispel2 !

2025-01-09 14:09 UTC, merged